name: HealthCheckIn

on:
  push:
    branches:
      - master
  watch:
    types: started
  workflow_dispatch:
  schedule:
    # 2am & 4am UTC correspond to 10am & 12pm
    - cron: 0 2,4 * * *

jobs:
  HealthCheckIn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - username: YUAN_ACCOUNT
            password: YUAN_PSW
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets[matrix.username] }}
          PASSWORD: ${{ secrets[matrix.password] }}
        run: |
          python3 check-in.py ${ACCOUNT} ${PASSWORD}
